
FROM mcr.microsoft.com/mssql/server:2019-latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Brussels

USER root

# Bundle config and env files
# RUN mkdir -p /usr/config
COPY mssql/entrypoint.sh /usr/config/entrypoint.sh
COPY mssql/configure-db.sh /usr/config/configure-db.sh
COPY mssql/ag.sql /usr/config/ag.sql
COPY mssql/ag-listener.sql /usr/config/ag-listener.sql
COPY mssql/configure-mssql.sh /usr/config/configure-mssql.sh
COPY mssql/enable-ha-and-dr.sh /usr/config/enable-ha-and-dr.sh
COPY env/miscpassword.env /usr/config/miscpassword.env

# Provision and install SQL Server
RUN chmod +x /usr/config/entrypoint.sh
RUN chmod +x /usr/config/configure-db.sh
RUN chmod +x /usr/config/configure-mssql.sh
RUN chmod +x /usr/config/enable-ha-and-dr.sh

RUN /bin/bash /usr/config/configure-mssql.sh
RUN /bin/bash /usr/config/enable-ha-and-dr.sh

EXPOSE 1433
EXPOSE 1500

USER mssql

ENTRYPOINT [ "/bin/bash", "/usr/config/entrypoint.sh" ]
