
FROM mcr.microsoft.com/mssql/server:2019-latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Brussels

USER root

COPY mssql/configure-mssql.sh /usr/config/configure-mssql.sh

# Provision and install SQL Server
RUN chmod +x /usr/config/configure-mssql.sh \
    && /usr/config/configure-mssql.sh \
    && rm -f /usr/config/configure-mssql.sh  # Remove the script after execution to reduce image size

WORKDIR /usr/config

# Bundle config source
COPY linux/entrypoint.sh /usr/config
COPY linux/configure-db.sh /usr/config
COPY linux/ag.sql /usr/config
COPY env/miscpassword.env /usr/config

# Copy and execute the MSSQL configuration script
COPY mssql/enable-ha-and-dr.sh /usr/config/enable-ha-and-dr.sh

# Enable HA and DR
RUN chmod +x /usr/config/enable-ha-and-dr.sh \
    && /usr/config/enable-ha-and-dr.sh \
    && rm -f /usr/config/enable-ha-and-dr.sh  # Remove script after execution to reduce image size

EXPOSE 1433

# switch to the mssql user
USER mssql

ENTRYPOINT [ "/bin/bash", "/usr/config/entrypoint.sh" ]
